### ISSUE TITLE
Broken in new patch

### ISSUE THREAD

**Issue by jkeywo** [rockyjvec/EasyAPI#9]
GridTerminalSystem.Blocks and GridTerminalSystem.BlockGroups have been removed.

Should be easy enough to fix up the compile errors in Refresh and GroupFilter. Blocks are now accessed from GetBlocks() and BlockGroups with GetBlockGroups().

It's working for me now but I'm not familiar enough with git hub to make a branch/merge request/whatever you call them.

**Comment by rockyjvec** [comment]
Thanks, I'll try to fix it later today.

**Comment by rockyjvec** [comment]
@jkeywo , thanks for letting me know about the problem and for providing the solution.  I have fixed it in the latest version in GitHub and in the Steam Workshop.  Let me know if you notice any other problems.
